name: Build Android APK (Kivy/Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Přepneme běhové JDK na 17 (nutné pro sdkmanager/cmdline-tools)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip curl
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Prepare Android SDK (aidl)
        env:
          SDK: ${{ github.workspace }}/.android-sdk
        run: |
          mkdir -p "$SDK/cmdline-tools"
          cd "$SDK/cmdline-tools"
          curl -fo cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" --licenses
          yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" \
            "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;25.2.9519653"

          echo "ANDROID_SDK_ROOT=$SDK" >> $GITHUB_ENV
          echo "ANDROID_HOME=$SDK" >> $GITHUB_ENV
          echo "$SDK/platform-tools" >> $GITHUB_PATH

      - name: Build APK
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: JirkaKara-android-apk
          path: bin/*.apk
